import * as React from "react";
import {
  Activity, ArrowRight, Bell, BookOpen, Check, CheckCircle2, CheckSquare, ChevronDown,
  ChevronRight, CircleAlert, ClipboardList, Clock3, Database, Headset, Home, Layers3,
  MoreHorizontal, Plus, Search, Settings, Sparkles, UserRound, X, Link2, History,
  ShieldCheck, Pencil, Ban, FileText
} from "lucide-react";

type View = "Dashboard" | "Demandas" | "Atividades" | "Requisitos" | "Soluções e Versões" | "Chamados" | "Conhecimento" | "Indicadores" | "Configurações";
type WizardType = "demanda" | "atividade";
type Status = "Em andamento" | "Em validação" | "Concluído" | "Pendente";

type RecordItem = {
  id: string; title: string; description: string; status: Status; context: string;
  solution: string; version: string; date: string; priority?: string; type: string;
};

const seed: RecordItem[] = [
  {id:"DEM-012",title:"Implementar autenticação de dois fatores",description:"Adicionar segundo fator ao acesso dos usuários.",status:"Em andamento",context:"Contexto completo",solution:"Portal de Atendimento",version:"v1.2.0",date:"18/09/2026",priority:"Alta",type:"Demanda"},
  {id:"DEM-011",title:"Melhorar navegação do dashboard",description:"Simplificar a navegação e reduzir etapas.",status:"Em validação",context:"Contexto completo",solution:"Portal de Atendimento",version:"v1.2.0",date:"17/09/2026",priority:"Média",type:"Demanda"},
  {id:"DEM-010",title:"Relatório de atendimento",description:"Novo relatório para acompanhamento do suporte.",status:"Concluído",context:"Contexto completo",solution:"Dashboard de Relatórios",version:"v2.1.0",date:"14/09/2026",priority:"Baixa",type:"Demanda"},
  {id:"REQ-014",title:"Recuperação de senha",description:"Usuário deve conseguir redefinir a senha sem intervenção do suporte.",status:"Em validação",context:"Vinculado à DEM-012",solution:"Portal de Atendimento",version:"v1.2.0",date:"20/09/2026",type:"Requisito"},
  {id:"REQ-015",title:"Notificação de atendimento",description:"Enviar confirmação após abertura do chamado.",status:"Concluído",context:"Vinculado à DEM-011",solution:"Portal de Atendimento",version:"v1.2.0",date:"19/09/2026",type:"Requisito"},
  {id:"CH-028",title:"Falha na autenticação",description:"Usuário relata erro ao acessar a área restrita.",status:"Em validação",context:"Contexto recuperado",solution:"Portal de Atendimento",version:"v1.2.0",date:"28/09/2026",priority:"Alta",type:"Chamado"},
  {id:"CH-027",title:"Relatório não carrega",description:"Tela de relatórios apresenta erro após atualização.",status:"Em andamento",context:"Versão relacionada",solution:"Dashboard de Relatórios",version:"v2.1.0",date:"27/09/2026",type:"Chamado"},
  {id:"CH-026",title:"Usuário sem acesso",description:"Permissão não aplicada após alteração de perfil.",status:"Concluído",context:"Conhecimento disponível",solution:"Portal de Atendimento",version:"v1.2.0",date:"25/09/2026",type:"Chamado"},
  {id:"KB-007",title:"Falha de autenticação na versão 1.2.0",description:"Procedimento validado para diagnosticar falhas de autenticação.",status:"Concluído",context:"Reutilizado 12 vezes",solution:"Portal de Atendimento",version:"v1.2.0",date:"28/09/2026",type:"Conhecimento"},
  {id:"KB-006",title:"Permissão de usuário",description:"Procedimento para revisar permissões após alteração de perfil.",status:"Concluído",context:"Reutilizado 7 vezes",solution:"Portal de Atendimento",version:"v1.2.0",date:"25/09/2026",type:"Conhecimento"},
];

const nav: {label: View; icon: React.ElementType}[] = [
  {label:"Dashboard",icon:Home},{label:"Demandas",icon:ClipboardList},{label:"Requisitos",icon:CheckSquare},
  {label:"Soluções e Versões",icon:Layers3},{label:"Chamados",icon:Headset},{label:"Conhecimento",icon:BookOpen}
];

function useRecords(){
  const [items,setItems]=React.useState<RecordItem[]>(()=>{
    try { const raw=localStorage.getItem("nexus-mvp-records"); return raw?JSON.parse(raw):seed; } catch { return seed; }
  });
  React.useEffect(()=>localStorage.setItem("nexus-mvp-records",JSON.stringify(items)),[items]);
  return [items,setItems] as const;
}

function StatusPill({status}:{status:Status}){ return <em className={"status-pill "+status.toLowerCase().replaceAll(" ","-")}>{status}</em>; }

function Navbar({active,onChange,onCreate}:{active:View;onChange:(v:View)=>void;onCreate:(t:WizardType)=>void}){
  const [more,setMore]=React.useState(false),[mobile,setMobile]=React.useState(false);
  const select=(v:View)=>{onChange(v);setMore(false);setMobile(false)};
  return <header className="nx-navbar">
    <button className="nx-nav-brand" onClick={()=>select("Dashboard")}><img src="/nexus-logo.svg" alt="NEXUS"/><div><strong>NEXUS</strong><small>CONEXÃO DE CONTEXTO</small></div></button>
    <button className="nx-mobile-toggle" onClick={()=>setMobile(v=>!v)} aria-label="Navegação"><span/><span/><span/></button>
    <div className={"nx-nav-content "+(mobile?"open":"")}>
      <nav className="nx-nav-links">{nav.map(({label,icon:Icon})=><button key={label} className={active===label?"active":""} onClick={()=>select(label)}><Icon size={14}/>{label}</button>)}
        <div className="nx-nav-more"><button className={["Atividades","Indicadores","Configurações"].includes(active)?"active":""} onClick={()=>setMore(v=>!v)}><MoreHorizontal size={14}/>Mais<ChevronDown size={11}/></button>
        {more&&<div className="nx-nav-dropdown">{(["Atividades","Indicadores","Configurações"] as View[]).map(v=><button key={v} onClick={()=>select(v)}>{v}</button>)}</div>}</div>
      </nav>
      <div className="nx-nav-actions"><button className="nx-nav-create" onClick={()=>onCreate("demanda")}><Plus size={14}/>Nova demanda</button><button className="global-search" onClick={()=>window.dispatchEvent(new CustomEvent("nexus:search"))}><Search size={15}/><span>Pesquisar</span><kbd>Ctrl K</kbd></button><button className="notification-icon"><Bell size={17}/><i/></button><button className="user nx-user-button"><span className="avatar"><UserRound size={14}/></span><span>Tester<small>USUÁRIO</small></span></button></div>
    </div>
  </header>;
}

function ContextStrip({item}:{item:RecordItem}){
 return <div className="mvp-context-strip"><div><span>CONTEXTO</span><strong>{item.solution}</strong></div><ChevronRight size={13}/><div><span>VERSÃO</span><strong>{item.version}</strong></div><ChevronRight size={13}/><div><span>ORIGEM</span><strong>{item.id}</strong></div><ChevronRight size={13}/><div><span>SUPORTE</span><strong>Contexto disponível</strong></div></div>;
}

function Detail({item,onClose,onUpdate}:{item:RecordItem;onClose:()=>void;onUpdate:(id:string,status:Status)=>void}){
 const isTicket=item.type==="Chamado";
 const [approved,setApproved]=React.useState(false);
 return <div className="mvp-overlay" onClick={onClose}><aside className="mvp-drawer" onClick={e=>e.stopPropagation()}>
   <div className="mvp-drawer-head"><div><span className="eyebrow">{item.type.toUpperCase()} · {item.id}</span><h2>{item.title}</h2><p>{item.description}</p></div><button onClick={onClose}><X size={18}/></button></div>
   <ContextStrip item={item}/>
   <div className="mvp-detail-body">
    <section className="mvp-detail-card"><div className="mvp-card-title"><div><span className="section-kicker">INFORMAÇÕES</span><h3>Registro</h3></div><StatusPill status={item.status}/></div><div className="mvp-fields"><div><span>Data</span><strong>{item.date}</strong></div><div><span>Prioridade</span><strong>{item.priority||"Normal"}</strong></div><div><span>Contexto</span><strong>{item.context}</strong></div><div><span>Solução</span><strong>{item.solution}</strong></div></div></section>
    <section className="mvp-detail-card"><div className="mvp-card-title"><div><span className="section-kicker">LINHA DO CONTEXTO</span><h3>Como esta informação chegou até aqui</h3></div><History size={17}/></div><div className="mvp-timeline"><span><b>Demanda</b> DEM-012</span><span><b>Requisito</b> REQ-014</span><span><b>Versão</b> {item.version}</span><span className="current"><b>{item.type}</b> {item.id}</span></div></section>
    {isTicket&&<section className="mvp-ai-card"><div className="mvp-ai-head"><span><Sparkles size={16}/> SUGESTÃO DA IA</span><em>Aguardando validação</em></div><h3>Possíveis caminhos de diagnóstico</h3><p>Com base no chamado e no contexto relacionado, foram identificados caminhos de análise. A sugestão não confirma a causa e precisa ser validada pelo responsável.</p><div className="mvp-suggestion"><strong>Possível causa</strong><span>Configuração de autenticação relacionada à versão {item.version}.</span><strong>Procedimento sugerido</strong><ol><li>Verificar configuração de autenticação.</li><li>Validar permissões do usuário afetado.</li><li>Comparar com o comportamento registrado no requisito relacionado.</li></ol></div><div className="mvp-evidence"><span><Link2 size={13}/> Evidências utilizadas</span><b>REQ-014</b><b>KB-007</b><b>{item.version}</b></div><div className="mvp-validation"><strong><ShieldCheck size={15}/> Validação humana</strong><div><button className="secondary-action" onClick={()=>setApproved(false)}><Pencil size={14}/> Editar</button><button className="primary" onClick={()=>{setApproved(true);onUpdate(item.id,"Concluído")}}><Check size={14}/> {approved?"Validado":"Aprovar sugestão"}</button><button className="mvp-reject" onClick={()=>setApproved(false)}><Ban size={14}/> Rejeitar</button></div></div></section>}
    {item.type==="Conhecimento"&&<section className="mvp-detail-card"><div className="mvp-card-title"><div><span className="section-kicker">REUTILIZAÇÃO</span><h3>Conhecimento validado</h3></div><CheckCircle2 size={17}/></div><p className="mvp-muted">Originado de atendimento e disponível para apoiar novos chamados relacionados à solução e versão.</p></section>}
   </div>
   <div className="mvp-drawer-footer"><button className="secondary-action" onClick={onClose}>Fechar</button>{isTicket&&<button className="primary" onClick={()=>onUpdate(item.id,"Concluído")}><CheckCircle2 size={14}/> Encerrar atendimento</button>}</div>
 </aside></div>
}

function Wizard({type,onClose,onCreate}:{type:WizardType;onClose:()=>void;onCreate:(r:RecordItem)=>void}){
 const demand=type==="demanda",steps=demand?["Identificação","Contexto","Objetivo","Revisão"]:["Identificação","Planejamento","Execução","Revisão"];
 const [step,setStep]=React.useState(0),[saved,setSaved]=React.useState(false),[data,setData]=React.useState<Record<string,string>>({});
 const set=(k:string,v:string)=>setData(d=>({...d,[k]:v}));
 const save=()=>{localStorage.setItem("nexus-"+type+"-draft",JSON.stringify({step,data,savedAt:new Date().toISOString()}));setSaved(true);setTimeout(()=>setSaved(false),1200)};
 const finish=()=>{save();onCreate({id:(demand?"DEM-":"ATV-")+String(Date.now()).slice(-3),title:data.titulo||"Novo registro",description:data.descricao||"Registro criado no NEXUS.",status:"Em andamento",context:"Contexto inicial",solution:data.solucao||"Portal de Atendimento",version:"v1.2.0",date:new Date().toLocaleDateString("pt-BR"),priority:data.prioridade||"Normal",type:demand?"Demanda":"Atividade"});};
 return <div className="wizard-overlay"><div className="wizard-modal mvp-wizard"><div className="wizard-header"><div><span className="section-kicker">NOVA {demand?"DEMANDA":"ATIVIDADE"}</span><h2>{demand?"Construir uma nova demanda":"Registrar atividade"}</h2><p>O contexto é salvo a cada etapa.</p></div><button className="close-button" onClick={onClose}><X size={18}/></button></div>
 <div className="stepper">{steps.map((s,i)=><React.Fragment key={s}><div className={"step "+(i===step?"active":i<step?"done":"")}><span>{i<step?<Check size={13}/>:i+1}</span><small>{s}</small></div>{i<steps.length-1&&<div className={"step-line "+(i<step?"done":"")}/>}</React.Fragment>)}</div>
 <div className="wizard-body">
 {step===0&&<div className="wizard-form"><div className="wizard-intro"><div className="wizard-intro-icon"><FileText size={18}/></div><div><strong>Comece pelo essencial</strong><span>Descreva a necessidade de forma objetiva.</span></div></div><label>Título<input value={data.titulo||""} onChange={e=>set("titulo",e.target.value)} placeholder={demand?"Ex.: Melhorar recuperação de senha":"Ex.: Validar regra de negócio"}/></label><label>Descrição<textarea value={data.descricao||""} onChange={e=>set("descricao",e.target.value)} rows={5} placeholder="O que precisa acontecer?"/></label></div>}
 {step===1&&<div className="wizard-form"><div className="wizard-intro"><div className="wizard-intro-icon"><Database size={18}/></div><div><strong>{demand?"Preserve o contexto":"Relacione o trabalho"}</strong><span>Estas informações acompanharão o registro no fluxo.</span></div></div><div className="form-grid"><label>{demand?"Área solicitante":"Demanda relacionada"}<input value={data.area||""} onChange={e=>set("area",e.target.value)} placeholder={demand?"Ex.: Atendimento":"DEM-012"}/></label><label>{demand?"Origem":"Responsável"}<input value={data.origem||""} onChange={e=>set("origem",e.target.value)} placeholder={demand?"Ex.: Suporte":"Nome do responsável"}/></label></div><label>Informações adicionais<textarea value={data.contexto||""} onChange={e=>set("contexto",e.target.value)} rows={5} placeholder="Regras, exemplos, referências ou observações..."/></label></div>}
 {step===2&&<div className="wizard-form"><div className="wizard-intro"><div className="wizard-intro-icon"><CheckSquare size={18}/></div><div><strong>{demand?"Defina o objetivo":"Planeje a execução"}</strong><span>Um registro claro facilita as próximas relações.</span></div></div><label>{demand?"Objetivo esperado":"Resultado esperado"}<textarea value={data.objetivo||""} onChange={e=>set("objetivo",e.target.value)} rows={4}/></label><div className="form-grid"><label>Prioridade<select value={data.prioridade||""} onChange={e=>set("prioridade",e.target.value)}><option value="">Selecionar</option><option>Alta</option><option>Média</option><option>Baixa</option></select></label><label>Solução relacionada<input value={data.solucao||""} onChange={e=>set("solucao",e.target.value)} placeholder="Portal de Atendimento"/></label></div></div>}
 {step===3&&<div className="review-box"><div className="review-icon"><CheckCircle2 size={24}/></div><h3>Revise o contexto antes de concluir</h3><p>O registro ficará disponível para os próximos estágios do NEXUS.</p><div className="review-summary"><span>Tipo</span><strong>{demand?"Demanda":"Atividade"}</strong><span>Título</span><strong>{data.titulo||"Não informado"}</strong><span>Contexto</span><strong>{data.contexto||"Contexto inicial"}</strong><span>Prioridade</span><strong>{data.prioridade||"Normal"}</strong></div></div>}
 </div><div className="wizard-footer"><span className={"save-status "+(saved?"visible":"")}><CheckCircle2 size={14}/> Salvo</span><span className="step-count">Etapa {step+1} de {steps.length}</span><div className="wizard-actions"><button className="secondary-action" onClick={step?()=>setStep(step-1):onClose}>{step?"Voltar":"Cancelar"}</button>{step<3?<button className="primary" onClick={()=>{save();setStep(s=>s+1)}}>Salvar e continuar <ChevronRight size={15}/></button>:<button className="primary" onClick={finish}>Concluir <Check size={15}/></button>}</div></div>
 </div></div>
}

function Module({view,items,onOpen,onCreate}:{view:View;items:RecordItem[];onOpen:(i:RecordItem)=>void;onCreate:(t:WizardType)=>void}){
 const [query,setQuery]=React.useState(""),[filter,setFilter]=React.useState("Todos");
 const moduleType=view==="Demandas"?"Demanda":view==="Requisitos"?"Requisito":view==="Chamados"?"Chamado":view==="Conhecimento"?"Conhecimento":view==="Atividades"?"Atividade":"";
 const list=moduleType?items.filter(i=>i.type===moduleType):items;
 const filtered=list.filter(i=>(filter==="Todos"||i.status===filter)&&((i.title+" "+i.id+" "+i.description).toLowerCase().includes(query.toLowerCase())));
 const canCreate=view==="Demandas"||view==="Atividades";
 const desc:Record<string,string>={Demandas:"Registre necessidades e preserve o contexto que dará origem às soluções.",Atividades:"Organize o trabalho mantendo cada atividade ligada ao contexto.",Requisitos:"Transforme demandas em requisitos rastreáveis e validáveis.",Chamados:"Atenda chamados recuperando o contexto produzido durante o desenvolvimento.",Conhecimento:"Consolide soluções validadas para reutilização no suporte.","Soluções e Versões":"Visualize soluções, versões e o contexto que será utilizado no suporte.",Indicadores:"Acompanhe indicadores relacionados ao fluxo de contexto.",Configurações:"Gerencie preferências e parâmetros do NEXUS."};
 return <main className="content nx-module-page"><div className="nx-breadcrumb"><button onClick={()=>window.dispatchEvent(new CustomEvent("nexus:go-dashboard"))}>Início</button><ChevronRight size={11}/><span>{view}</span></div><div className="page-heading nx-module-heading"><div><span className="eyebrow">{view.toUpperCase()}</span><h1>{view}</h1><p>{desc[view]}</p></div><div className="nx-page-actions">{canCreate&&<button className="primary" onClick={()=>onCreate(view==="Demandas"?"demanda":"atividade")}><Plus size={15}/>Novo {view==="Demandas"?"registro":"atividade"}</button>}{view==="Chamados"&&<button className="secondary-action" onClick={()=>{const t=items.find(i=>i.id==="CH-028");if(t)onOpen(t)}}><Headset size={14}/>Atender chamado</button>}</div></div>
 <div className="nx-module-summary"><div><strong>{list.length}</strong><span>registros</span></div><div><strong>{list.filter(i=>i.status==="Em validação").length}</strong><span>aguardando validação</span></div><div><strong>{Math.round(list.filter(i=>i.context.includes("Contexto")||i.context.includes("Vinculado")).length/Math.max(list.length,1)*100)}%</strong><span>com contexto relacionado</span></div></div>
 <div className="module-panel nx-module-panel"><div className="module-toolbar nx-module-toolbar"><div className="module-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar no módulo..."/></div><div className="nx-toolbar-filters">{["Todos","Em andamento","Em validação","Concluído"].map(f=><button key={f} className={"nx-filter "+(filter===f?"active":"")} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="nx-list-head"><span>Registro</span><span>Contexto</span><span>Status</span><span/></div>{filtered.map(item=><button className="nx-module-row" key={item.id} onClick={()=>onOpen(item)}><span className="nx-record-main"><strong>{item.id} · {item.title}</strong><small>{item.description}</small></span><span className="nx-record-context"><i/>{item.context}</span><StatusPill status={item.status}/><ArrowRight size={14}/></button>)}</div>{!filtered.length&&<div className="mvp-empty"><Search size={20}/><strong>Nenhum registro encontrado</strong><span>Tente outro termo ou filtro.</span></div>}<div className="nx-module-hint"><Database size={14}/><span><strong>O contexto acompanha o registro.</strong> Abra qualquer item para visualizar relações, histórico e informações utilizadas no fluxo.</span></div></main>;
}

function Dashboard({items,onChange,onOpen,onCreate}:{items:RecordItem[];onChange:(v:View)=>void;onOpen:(i:RecordItem)=>void;onCreate:(t:WizardType)=>void}){
 const tickets=items.filter(i=>i.type==="Chamado"),demands=items.filter(i=>i.type==="Demanda"),reqs=items.filter(i=>i.type==="Requisito"),knowledge=items.filter(i=>i.type==="Conhecimento");
 return <main className="content dashboard-content nexus-dashboard"><section className="nx-welcome"><div><span className="eyebrow">VISÃO GERAL</span><h1>Olá, Tester!</h1><p>O NEXUS preserva o contexto da solução para que ele acompanhe o atendimento.</p></div><div className="nx-welcome-actions"><button className="secondary-action" onClick={()=>onCreate("atividade")}><Activity size={15}/>Nova atividade</button><button className="primary" onClick={()=>onCreate("demanda")}><Plus size={15}/>Nova demanda</button></div></section>
 <section className="nx-stats"><button className="nx-stat" onClick={()=>onChange("Demandas")}><span className="nx-stat-icon blue"><ClipboardList size={17}/></span><span className="nx-stat-label">Demandas</span><strong>{demands.length}</strong><small>com contexto preservado</small></button><button className="nx-stat" onClick={()=>onChange("Requisitos")}><span className="nx-stat-icon green"><CheckSquare size={17}/></span><span className="nx-stat-label">Requisitos</span><strong>{reqs.length}</strong><small>{reqs.filter(i=>i.status==="Em validação").length} em validação</small></button><button className="nx-stat" onClick={()=>onChange("Chamados")}><span className="nx-stat-icon orange"><Headset size={17}/></span><span className="nx-stat-label">Chamados</span><strong>{tickets.length}</strong><small>{tickets.filter(i=>i.status!=="Concluído").length} em atendimento</small></button><button className="nx-stat" onClick={()=>onChange("Conhecimento")}><span className="nx-stat-icon purple"><BookOpen size={17}/></span><span className="nx-stat-label">Conhecimentos</span><strong>{knowledge.length}</strong><small>soluções validadas</small></button></section>
 <section className="nx-dashboard-grid"><div className="nx-main-column"><article className="panel nx-panel"><div className="nx-panel-head"><div><span className="section-kicker">FLUXO DO NEXUS</span><h2>Contexto da solução</h2><p>Acompanhe como a informação atravessa desenvolvimento, suporte e conhecimento.</p></div></div><div className="mvp-flow"><span className="done">Demanda</span><ArrowRight size={13}/><span className="done">Requisitos</span><ArrowRight size={13}/><span className="done">Versão</span><ArrowRight size={13}/><span className="current">Chamado</span><ArrowRight size={13}/><span>IA sugere</span><ArrowRight size={13}/><span>Humano valida</span><ArrowRight size={13}/><span>Conhecimento</span></div><div className="mvp-flow-note"><Database size={15}/><div><strong>82% dos registros possuem contexto relacionado</strong><span>O objetivo é recuperar o contexto antes da análise do suporte.</span></div></div></article>
 <article className="panel nx-panel"><div className="nx-panel-head compact"><div><span className="section-kicker">CHAMADOS</span><h2>Atendimento que precisa de atenção</h2></div><button className="text-button" onClick={()=>onChange("Chamados")}>Ver todos <ArrowRight size={12}/></button></div>{tickets.filter(t=>t.status!=="Concluído").slice(0,3).map(t=><button className="mvp-ticket-row" key={t.id} onClick={()=>onOpen(t)}><span className="nx-priority-icon orange"><CircleAlert size={15}/></span><span><strong>{t.id} · {t.title}</strong><small>{t.context} · {t.version}</small></span><StatusPill status={t.status}/><ArrowRight size={14}/></button>)}</article></div>
 <aside className="nx-side-column"><article className="panel nx-panel nx-quick-panel"><div className="nx-panel-head compact"><div><span className="section-kicker">AÇÕES RÁPIDAS</span><h2>Comece por aqui</h2></div></div><button onClick={()=>onCreate("demanda")}><span className="nx-action-icon blue"><Plus size={16}/></span><span><strong>Nova demanda</strong><small>Registrar uma necessidade</small></span><ArrowRight size={13}/></button><button onClick={()=>onCreate("atividade")}><span className="nx-action-icon green"><Activity size={16}/></span><span><strong>Nova atividade</strong><small>Adicionar trabalho</small></span><ArrowRight size={13}/></button><button onClick={()=>onChange("Chamados")}><span className="nx-action-icon orange"><Headset size={16}/></span><span><strong>Atender chamado</strong><small>Recuperar contexto</small></span><ArrowRight size={13}/></button></article><article className="panel nx-context-card"><div className="nx-context-head"><div><span className="section-kicker">CONTEXTO</span><h2>Continuidade</h2></div><Database size={17}/></div><div className="nx-context-body"><div className="nx-context-ring"><strong>82%</strong><span>com contexto</span></div><div className="nx-context-copy"><strong>O contexto acompanha a solução</strong><p>Relacionamentos ajudam o suporte a recuperar informações antes da sugestão.</p></div></div><div className="nx-context-flow"><span>Desenvolvimento</span><ArrowRight size={12}/><span>Suporte</span><ArrowRight size={12}/><span>Conhecimento</span></div></article></aside></section>
 <section className="nx-bottom-grid"><article className="panel nx-panel nx-activity-panel"><div className="nx-panel-head compact"><div><span className="section-kicker">PRÓXIMAS AÇÕES</span><h2>O que precisa da sua atenção</h2></div></div><div className="mvp-attention"><button onClick={()=>onOpen(items.find(i=>i.id==="CH-028") || tickets[0] || {id:"CH-000",title:"Nenhum chamado",description:"",status:"Pendente",context:"Sem contexto",solution:"",version:"",date:"",type:"Chamado"})}><CircleAlert size={15}/><span><strong>CH-028 aguarda validação</strong><small>A sugestão da IA ainda precisa de decisão humana.</small></span><ChevronRight size={14}/></button><button onClick={()=>onChange("Requisitos")}><CheckSquare size={15}/><span><strong>Requisitos em validação</strong><small>Revise informações antes de avançar.</small></span><ChevronRight size={14}/></button><button onClick={()=>onChange("Conhecimento")}><BookOpen size={15}/><span><strong>Conhecimento disponível para reuso</strong><small>2 soluções podem apoiar novos chamados.</small></span><ChevronRight size={14}/></button></div></article><article className="panel nx-panel"><div className="nx-panel-head compact"><div><span className="section-kicker">RASTREABILIDADE</span><h2>Uma informação, vários contextos</h2></div></div><div className="mvp-trace"><div><strong>DEM-012</strong><span>Demanda</span></div><ArrowRight size={14}/><div><strong>REQ-014</strong><span>Requisito</span></div><ArrowRight size={14}/><div><strong>v1.2.0</strong><span>Versão</span></div><ArrowRight size={14}/><div><strong>CH-028</strong><span>Chamado</span></div><ArrowRight size={14}/><div><strong>KB-007</strong><span>Conhecimento</span></div></div></article></section>
 </main>;
}

export default function NexusMVP(){
 const [active,setActive]=React.useState<View>("Dashboard"),[wizard,setWizard]=React.useState<WizardType|null>(null),[detail,setDetail]=React.useState<RecordItem|null>(null),[items,setItems]=useRecords(),[search,setSearch]=React.useState(false);
 React.useEffect(()=>{const s=()=>setSearch(true),d=()=>setActive("Dashboard"),k=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setSearch(true)}if(e.key==="Escape"){setSearch(false);setWizard(null);setDetail(null)}};window.addEventListener("nexus:search",s);window.addEventListener("nexus:go-dashboard",d);window.addEventListener("keydown",k);return()=>{window.removeEventListener("nexus:search",s);window.removeEventListener("nexus:go-dashboard",d);window.removeEventListener("keydown",k)}},[]);
 const add=(r:RecordItem)=>{setItems(x=>[r,...x]);setWizard(null);setActive(r.type==="Demanda"?"Demandas":"Atividades")};
 const update=(id:string,status:Status)=>setItems(x=>x.map(i=>i.id===id?{...i,status}:i));
 return <div className="app"><div className="main"><Navbar active={active} onChange={setActive} onCreate={setWizard}/>{active==="Dashboard"?<Dashboard items={items} onChange={setActive} onOpen={setDetail} onCreate={setWizard}/>:<Module view={active} items={items} onOpen={setDetail} onCreate={setWizard}/>}</div>{wizard&&<Wizard type={wizard} onClose={()=>setWizard(null)} onCreate={add}/>} {detail&&<Detail item={detail} onClose={()=>setDetail(null)} onUpdate={update}/>} {search&&<GlobalSearch items={items} onClose={()=>setSearch(false)} onOpen={setDetail}/>}</div>;
}

function GlobalSearch({items,onClose,onOpen}:{items:RecordItem[];onClose:()=>void;onOpen:(i:RecordItem)=>void}){
 const [q,setQ]=React.useState(""),r=items.filter(i=>(i.id+" "+i.title+" "+i.description+" "+i.solution).toLowerCase().includes(q.toLowerCase())).slice(0,6);
 return <div className="search-overlay" onClick={onClose}><div className="search-dialog mvp-search" onClick={e=>e.stopPropagation()}><div className="search-dialog-head"><Search size={16}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Pesquisar no contexto do NEXUS..."/><button onClick={onClose}><X size={16}/></button></div>{q?<div className="mvp-search-results">{r.map(i=><button key={i.id} onClick={()=>{onOpen(i);onClose()}}><span><strong>{i.id} · {i.title}</strong><small>{i.type} · {i.solution} · {i.version}</small></span><ArrowRight size={14}/></button>)}{!r.length&&<div className="search-empty"><Search size={22}/><strong>Nenhum resultado</strong><span>Não encontramos registros para “{q}”.</span></div>}</div>:<div className="search-empty"><Search size={22}/><strong>Pesquisa global</strong><span>Busque demandas, requisitos, chamados e conhecimentos pelo contexto.</span></div>}</div></div>;
}
